mfdbprg/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    # URL "admin/" je namapováno na administrační rozhraní webu
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('', RedirectView.as_view(url='movies/')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('films/', views.FilmListView.as_view(), name='films_list'),
    path('films/genres/<str:genre_name>', views.FilmListView.as_view(), name='film_genre'),
    path('films/<int:pk>', views.FilmDetailView.as_view(), name='film_detail'),
    path('films/create', views.FilmCreate.as_view(), name='film_create'),
    path('films/<int:pk>/update', views.FilmUpdate.as_view(), name='film_update')
]

movies/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.urls import reverse

def attachment_path(instance, filename):
    return 'film/' + str(instance.film.id) + '/attachments/' + filename


class Genre(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name='Genre name',
    help_text='Enter a film genre (e.g. sci-fi, comedy)')

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class Film(models.Model):
    title = models.CharField(max_length=200, verbose_name='Title')
    plot = models.TextField(blank=True, null=True, verbose_name='Plot')
    release_date = models.DateField(blank=True, null=True,
                                    help_text='Please use the following format: <em>YYYYMM-DD</em>.',
                                    verbose_name='Release date')
    poster = models.ImageField(upload_to='film/posters/%Y/%m/%d/',blank=True,
                               verbose_name='Poster')
    runtime = models.IntegerField(blank=True, null=True,
                                  help_text='Please enter an integer value (minutes)',
                                  verbose_name='Runtime')
    rate = models.FloatField(default=5.0,
                             validators=[MinValueValidator(1.0), MaxValueValidator(10.0)],
                             null=True, help_text='Please enter an float value (range 1.0 - 10.0)',
                             verbose_name='Rate')
    genres = models.ManyToManyField(Genre, help_text='Select a genre for this film')

    class Meta:
        ordering = ['-release_date', 'title']

    def __str__(self):
        return f'{self.title}, year: {str(self.release_date.year)}, rate:{str(self.rate)}'

    def get_absolute_url(self):
        return reverse('film_detail', args=[str(self.id)])


class Attachment(models.Model):
    title = models.CharField(max_length=200, verbose_name='Title')
    last_update = models.DateTimeField(auto_now=True)
    file = models.FileField(upload_to=attachment_path, null=True, verbose_name='File')
    TYPE_OF_ATTACHMENT = (
        ('audio', 'Audio'),
        ('image', 'Image'),
        ('text', 'Text'),
        ('video', 'Video'),
        ('other', 'Other'),
    )
    type = models.CharField(max_length=10, choices=TYPE_OF_ATTACHMENT, blank=True,
        default='image', help_text='Select allowed attachment type',
        verbose_name='Attachment type')
    film = models.ForeignKey(Film, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-last_update', 'type']

    def __str__(self):
        return f'{self.title}, ({self.type})'

movies/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from .models import Film


class FilmModelForm(ModelForm):
    def clean_runtime(self):
       data = self.cleaned_data['runtime']
       if data <= 0 or data > 1000:
           raise ValidationError('Neplatná délka filmu')
       return data

    class Meta:
        model = Film
        fields = ['title', 'plot', 'release_date', 'runtime', 'poster', 'rate', 'genres']
        labels = {'title': 'Název filmu', 'plot': 'Stručný děj'}

movies/views.py
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from movies.models import Film, Genre
from movies.forms import FilmModelForm

def index(request):
    context = {
        'num_films': Film.objects.all().count(),
        'films': Film.objects.order_by('-release_date')[:3],
        'top_ten': Film.objects.order_by('-rate')[:10],
        'genres': Genre.objects.order_by('name').all()
    }
    return render(request, 'index.html', context=context)


class FilmListView(ListView):
    model = Film
    context_object_name = 'films'
    template_name = 'film/list.html'

    def get_queryset(self):
        if 'genre_name' in self.kwargs:
            return Film.objects.filter(genres__name=self.kwargs['genre_name']).all()
        else:
            return Film.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['num_films'] = len(self.get_queryset())
        if 'genre_name' in self.kwargs:
            context['view_title'] = self.kwargs['genre_name']
        else:
            context['view_title'] = 'Filmy'
        return context



class FilmDetailView(DetailView):
    model = Film
    context_object_name = 'film_detail'
    template_name = 'film/detail.html'


class GenreListView(ListView):
    model = Genre
    template_name = 'blocks/genre_list.html'
    context_object_name = 'genres'
    queryset = Genre.objects.order_by('name').all()


class NewFilmListView(ListView):
    model = Film
    template_name = 'blocks/new_films.html'
    context_object_name = 'films'
    queryset = Film.objects.order_by('-release_date').all()


class FilmCreate(CreateView):
   model = Film
   fields = ['title', 'plot', 'release_date', 'runtime', 'poster', 'rate', 'genres']
   initial = {'rate': '5'}


class FilmUpdate(UpdateView):
    model = Film
    template_name = 'movies/film_bootstrap_form.html'
    form_class = FilmModelForm
    #fields = '__all__'

movies/templates/base.html
<!DOCTYPE html>
<html lang="cs">
<head>
    <title>{% block title %}Filmotéka{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    {% block css %}{% endblock %}
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
{% include 'page/header.html' %}
{% include 'page/navbar.html' %}
<div class="container-fluid">
    {% block content %}{% endblock %}
</div>
{% include 'page/footer.html' %}
<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<!-- Popper JS -->
<script
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
{% block scripts %}{% endblock %}
</body>
</html>

movies/templates/blocks/genre_list.html
<ul>
    {% for genre in genres %}
        <li><a href="{% url 'film_genre' genre.name %}">{{ genre.name }}</a> <span class="badge badge-info">{{ genre.film_set.count }}</span></li>
    {% endfor %}
</ul>

movies/templates/blocks/new_films.html
{% load mathfilters %}
<div>
    {% for film in films %}
        <div class="row mb-4 border-bottom">
            <div class="col-md-2">
                {% if film.poster %}
                <a href="{% url 'film_detail' film.pk %}">
                <img src="{{ film.poster.url }}" alt="Plakát k filmu"
                     class="img-fluid">
                </a>
                {% endif %}
            </div>
            <div class="col-md-8">
                <h4><a href="{% url 'film_detail' film.pk %}">{{ film.title|upper }}</a></h4>
                <p>{{ film.plot|truncatewords:30 }}</p>
                <p>Stopáž: {{ film.runtime }} min.,
                    datum uvedení: {{ film.release_date|date:'d. m. Y' }}</p>
                <p>Žánry: {% for genre in film.genres.all %}
                    <a href="#" class="btn btn-info">{{ genre.name }}</a>
                {% endfor %}</p>
            </div>
            <div class="col-md-2">
                <span class="display-4">{{ film.rate }}</span>
                <div class="progress">
                    <div class="progress-bar bg-info"
                         style="width:{{ film.rate|mul:'10'|floatformat }}%"></div>
                </div>
            </div>
        </div>
    {% endfor %}
</div>

movies/templates/blocks/top_ten.html
{% load mathfilters %}
<ol>
    {% for film in top_ten %}
    <li><a href="{% url 'film_detail' film.pk %}">{{ film.title }}</a> ({{ film.rate|mul:'10'|floatformat }} %)</li>
    {% endfor %}
</ol>

movies/templates/film/detail.html
{% extends "base.html" %}
{% block title %}Detail filmu{% endblock %}

<!-- Vložení externího CSS pro knihovnu Lightbox for Bootstrap -->
{% block css %}
 <link href="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.css" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="row mb-3">
        <div class="col-sm-12 bg-warning">
            <h2 class="display-4 text-center">Podrobné informace</h2>
        </div>
    </div>
    <div class="row mt-5 mb-3">
        <div class="col-lg-6 mb-3">
            <h2 class="display-4 mb-3">{{ film_detail.title }}</h2>
            <div class="bg-secondary text-light p-2 mb-3">
                Rok vzniku: {{ film_detail.release_date.year }}, stopáž: {{ film_detail.runtime }} minut,
                <!-- Řešení zobrazení hodnocení filmu ve formě hvězdiček -->
                {% with ''|center:film_detail.rate as range %}
                    {% for _ in range %}★{% endfor %}
                {% endwith %}
                <b>{{ film_detail.rate }}</b>
            </div>
            <div class="row">
                <div class="col-md-9">{{ film_detail.plot }}</div>
                <div class="col-md-3">
                    {% if film_detail.poster %}
                        <a href="{{ film_detail.poster.url }}" data-toggle="lightbox" datagallery="gallery">
                            <img src="{{ film_detail.poster.url }}" class="img-fluid"
                                 alt="Plakát k filmu">
                        </a>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-lg-6 bg-light p-3">
            <h3 class="border-bottom pb-3 text-secondary text-center textuppercase">Fotogalerie</h3>
            <div class="row">
                <!-- Zobrazení fotogalerie k příslušnému filmu -->
                {% for image in film_detail.attachment_set.all %}
                    <div class="col-lg-6 col-xl-4">
                        <a href="{{ image.file.url }}" data-toggle="lightbox" datagallery="gallery">
                            <img src="{{ image.file.url }}" class="img-fluid img-thumbnail" alt="{{image.title }}">
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

<!-- Vložení externího JS pro knihovnu Lightbox for Bootstrap -->
{% block scripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.min.js"></script>
<script>
 $(document).on("click", '[data-toggle="lightbox"]', function(event) {
    event.preventDefault();
    $(this).ekkoLightbox();
 });
</script>
{% endblock %}

movies/templates/film/list.html
<!-- Dědí základní šablonu base.html -->
{% extends "base.html" %}
<!-- Vložení informace do bloku titulu stránky -->
{% block title %}{{ view_title }}{% endblock %}
<!-- Obsahový blok stránky -->
{% block content %}
    <div class="row mb-3">
        <div class="col-sm-12 bg-warning">
            <h2 class="display-4 text-center">Seznam filmů</h2>
        </div>
    </div>
    <div class="row">
        <!-- Postupné načtení filmů z proměnné films_list -->
        {% for film in films %}
            <div class="col-sm-6 col-md-4 col-lg-3 col-xl-2">
                <div class="card">
                    {% if film.poster %}
                        <img class="card-img-top" src="{{ film.poster.url }}" alt="{{ film.title }}">
                    {% endif %}
                    <div class="card-body">
                        <!-- Odkaz ještě musí být doplněn o adresu stránky s detailem filmu -->
                        <h4 class="card-title"><a href="{% url 'film_detail' film.pk %}">{{ film.title }}</a></h4>
                        <!-- Výpis všech žánrů filmu - odkaz bude posléze ukazovat všechny filmy daného
                       žánru -->
                        <p class="card-text">{% for genre in film.genres.all %}
                            <a href="{% url 'film_genre' genre.name %}" class="btn btn-light">{{ genre.name }}</a> {% endfor %}</p>
                        <!-- Odkaz ještě musí být doplněn o adresu stránky s detailem filmu -->
                        <a href="{% url 'film_detail' film.pk %}" class="btn btn-primary">Podrobnosti</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

movies/templates/index-zaloha.html
<!DOCTYPE html>
<html lang="cs">
<head>
    <meta charset="UTF-8">
    <title>MFDB</title>
</head>
<body>
    <h1>MFDB</h1>
    {%  for film in films %}
        <div class="card">
            <h2>{{ film.title }}</h2>
            <p><img src="{{ film.poster.url }}" alt="{{ film.title }}"></p>
            <p>Rok: {{ film.release_date.year }}, Hodnocení: {{ film.rate }}</p>
            <p>{{ film.plot }}</p>
        </div>
    {% endfor %}
    <p>Počet filmů: {{ num_films }}</p>
</body>
</html>

movies/templates/index.html
{% extends "base.html" %}


{% block content %}
<div class="row">
    <div class="col-md-4">
        <h3 class="bg-danger text-center text-uppercase p-3 text-white">Nové filmy</h3>
        {% include "blocks/new_films.html" %}
    </div>
    <div class="col-md-4">
        <h3 class="bg-info text-center text-uppercase p-3 text-white">Top ten</h3>
        {% include "blocks/top_ten.html" %}
    </div>
    <div class="col-md-4">
        <h3 class="bg-success text-center text-uppercase p-3 text-white">Seznam žánrů</h3>
        {% include "blocks/genre_list.html" %}
    </div>
</div>
{% endblock %}

movies/templates/movies/film_bootstrap_form.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}Editace filmu{% endblock %}

{% block content %}
<div class="row mb-3">
    <div class="col-sm-12 bg-warning">
        <h2 class="display-4 text-center">Editace filmu</h2>
    </div>
</div>
<div class="row mt-5 mb-3">
    <div class="container">
        <form method="post" novalidate>
            {% csrf_token %}

            {% for hidden_field in form.hidden_fields %}
              {{ hidden_field }}
            {% endfor %}

            {% if form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
                {% for error in form.non_field_errors %}
                  {{ error }}
                {% endfor %}
            </div>
            {% endif %}

            {% for field in form.visible_fields %}
            <div class="form-group">
                {{ field.label_tag }}

                {% if form.is_bound %}
                  {% if field.errors %}
                    {% render_field field class="form-control is-invalid" %}
                    {% for error in field.errors %}
                      <div class="invalid-feedback">
                          {{ error }}
                      </div>
                    {% endfor %}
                  {% else %}
                    {% render_field field class="form-control is-valid" %}
                  {% endif %}
                {% else %}
                  {% render_field field class="form-control" %}
                {% endif %}

                {% if field.help_text %}
                <small class="form-text text-muted">{{ field.help_text }}</small>
                {% endif %}
            </div>
            {% endfor %}

            <button class="btn btn-primary" type="submit">Potvrdit</button>
            <button class="btn btn-secondary" onclick="javascript:history.back();">Zrušit</button>
        </form>
    </div>
</div>
{% endblock %}

movies/templates/movies/film_form.html
{% extends 'base.html' %}

{% block title %}Editace filmu{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-12">
            <h2>Editace filmu</h2>
        </div>
    </div>
    <div class="row">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>
            <input type="submit" value="Submit">
        </form>
    </div>
{% endblock %}

movies/templates/page/footer.html
{% load static %}
<footer class="container-fluid text-center">
    <hr>
    <p><img src="{% static 'img/skola-logo.png' %}" alt="Logo školy"></p>
    <p>&copy; 2021 - SŠPU Opava</p>
</footer>

movies/templates/page/header.html
<header class="jumbotron-fluid p-5 text-center bg-dark">
    <h1 class="text-white text-uppercase display-3">Malá filmová databáze</h1>
</header>

movies/templates/page/navbar.html
<nav class="navbar navbar-expand-md bg-dark navbar-dark">
    <!-- Brand -->
    <a class="navbar-brand text-warning" href="{% url 'index' %}">MFD</a>
    <!-- Toggler/collapsibe Button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" datatarget="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>
    <!-- Navbar links -->
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'index' %}">Úvodní stránka</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'films_list' %}">Filmy</a>
            </li>
            <!-- Dropdown -->
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                Žánry
              </a>
              <div class="dropdown-menu">
                 {% for genre in genres %}
                    <a class="dropdown-item" href="{% url 'film_genre' genre.name %}">
                        {{ genre.name }}</a>
                 {% endfor %}
              </div>
            </li>

        </ul>
    </div>
</nav>